# Generated by Django 2.0.8 on 2021-07-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20180507_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='username',
        ),
        migrations.AlterField(
            model_name='username',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
